---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-php-app
spec:
  template:
    spec:
      containers:
        - name: app
          volumeMounts:
            - name: data
              mountPath: /app/src
      volumes:
      - name: data
        configMap:
          name: phpinfo
